import type { Metadata } from 'next';
import { ubuntu, tilt_neon, manrope } from './fonts';
import './globals.css';
import Navigation from './components/Navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.variable} ${manrope.variable} ${tilt_neon.variable}`}
        suppressHydrationWarning={true}
      >
        <main className="w-screen h-screen bg-gradient-to-b from-blue-50 to-red-100 p-3 overflow-hidden">
          <Navigation />
          {children}
        </main>
      </body>
    </html>
  );
}
